### ISSUE TITLE
Ability to set the snap channel

### ISSUE THREAD

**Issue by hskrtich** [capitanh/microk8s_ansible_role#2]
Hi, can you add a var to let me set the snap channel when installing microk8s?

I need to downgrade to the previous version since I'm running into an error in 1.29. The current work around is to go back to 1.28 but that isn't possible with your role atm.

Thank you!

**Comment by capitanh** [comment]
Merged your PR, thanks!

**Comment by capitanh** [comment]
Merged your PR, thanks!
